// ignore_for_file: non_constant_identifier_names

import 'dart:ui';

List ContainColor = [
  const Color(0xffBBECD7),
  const Color(0xffD5DDFF),
  const Color(0xffFEE3E3),
  const Color(0xffFEF0D7),
  const Color(0xffBBECD7),
  const Color(0xffD5DDFF),
  const Color(0xffFEE3E3),
  const Color(0xffFEF0D7),
  const Color(0xffBBECD7),
  const Color(0xffD5DDFF),
  const Color(0xffFEE3E3),
  const Color(0xffFEF0D7),
  const Color(0xffBBECD7),
  const Color(0xffD5DDFF),
  const Color(0xffFEE3E3),
];
List RtangleColor = [
  const Color(0xffD6F3E7),
  const Color(0xffE6EAFF),
  const Color(0xffFFEEED),
  const Color(0xffFFF6E9),
  const Color(0xffD6F3E7),
  const Color(0xffE6EAFF),
  const Color(0xffFFEEED),
  const Color(0xffFFF6E9),
  const Color(0xffD6F3E7),
  const Color(0xffE6EAFF),
  const Color(0xffFFEEED),
  const Color(0xffFFF6E9),
  const Color(0xffD6F3E7),
  const Color(0xffE6EAFF),
  const Color(0xffFFEEED),
];

List title = [
  """Online Loans""",
  """How Do Loans Work?""",
  """How Loan Finance...""",
  """How Loan Interest...""",
  """What to expect when you...""",
  """How much loans cost""",
  """What happens if you can’t""",
  """You can’t pay back a loan...""",
  """Do you really need to borrow?""",
  """Cheaper alternatives to...""",
  """Short-term/payday loans""",
  """What is a online loan?""",
  """Why choose a online loan...""",
  """Loan Changes Retracted""",
  """What to ask a online lender""",
];
List images = [
  "asset/image/icons/loan type icon 1.png",
  "asset/image/icons/loan type icon 2.png",
  "asset/image/icons/loan type icon 3.png",
  "asset/image/icons/loan type icon 4.png",
  "asset/image/icons/loan type icon 5.png",
  "asset/image/icons/loan type icon 6.png",
  "asset/image/icons/loan type icon 7.png",
  "asset/image/icons/loan type icon 8.png",
  "asset/image/icons/loan type icon 9.png",
  "asset/image/icons/loan type icon 10.png",
  "asset/image/icons/loan type icon 11.png",
  "asset/image/icons/loan type icon 12.png",
  "asset/image/icons/loan type icon 13.png",
  "asset/image/icons/loan type icon 14.png",
  "asset/image/icons/loan type icon 15.png",
];
List titlecolor = [
  const Color(0xff244A44),
  const Color(0xff35295A),
  const Color(0xff552F3B),
  const Color(0xff372808),
  const Color(0xff244A44),
  const Color(0xff35295A),
  const Color(0xff552F3B),
  const Color(0xff372808),
  const Color(0xff244A44),
  const Color(0xff35295A),
  const Color(0xff552F3B),
  const Color(0xff372808),
  const Color(0xff244A44),
  const Color(0xff35295A),
  const Color(0xff552F3B),
];
